import pluginVue from 'eslint-plugin-vue'

export default [
    {
        ignores: [
            'dist/*',
            'node_modules/*',
        ],
    },
    ...pluginVue.configs['flat/recommended'],
    {
        rules: {
            'brace-style': ['warn', 'stroustrup'],
            'comma-dangle': ['warn', {
                arrays: 'always-multiline',
                objects: 'always-multiline',
                imports: 'always-multiline',
                exports: 'always-multiline',
                functions: 'never',
            }],
            'eol-last': ['warn', 'always'],
            indent: ['warn', 4, { SwitchCase: 1 }],
            'linebreak-style': ['error', 'unix'],
            'newline-before-return': 'warn',
            'no-multiple-empty-lines': 'warn',
            'no-trailing-spaces': 'warn',
            'no-unused-vars': 'warn',
            'no-useless-computed-key': 'warn',
            'operator-linebreak': ['warn', 'before'],
            'padded-blocks': ['warn', 'never'],
            'quote-props': ['warn', 'as-needed'],
            quotes: ['warn', 'single', { avoidEscape: false }],
            'space-before-blocks': 'warn',
            'space-before-function-paren': ['warn', {
                anonymous: 'never',
                named: 'never',
                asyncArrow: 'always',
            }],
            'space-infix-ops': 'warn',
            'vue/attribute-hyphenation': 'warn',
            'vue/attributes-order': 'off',
            'vue/camelcase': 'warn',
            'vue/comma-dangle': ['warn', 'always-multiline'],
            'vue/eqeqeq': 'warn',
            'vue/html-indent': ['warn', 4, { alignAttributesVertically: false }],
            'vue/html-quotes': ['warn', 'double', { avoidEscape: false }],
            'vue/html-self-closing': 'warn',
            'vue/max-attributes-per-line': 'off',
            'vue/no-multiple-template-root': 0,
            'vue/no-mutating-props': 'error',
            'vue/no-unused-components': 'warn',
            'vue/no-use-v-if-with-v-for': 'error',
            'vue/order-in-components': 'off',
            'vue/require-prop-types': 'warn',
            'vue/require-v-for-key': 'error',
            'vue/script-indent': ['warn', 4, { switchCase: 1 }],
            'vue/singleline-html-element-content-newline': 'off',
            'vue/this-in-template': 'warn',
            'vue/multi-word-component-names': 'warn',
            yoda: 'warn',
        },
    },
    {
        files: ['src/views/**/*.vue'],
        rules: {
            'vue/multi-word-component-names': 'off',
        },
    },
]
